### PR TITLE
Hw wk01d05

### PR DESCRIPTION
**Pull request by mkikegawa**

### CODE REVIEW

**Comment by mkikegawa** [comment]
{
 "Comfortability":   4,
 "Completeness":  5,
 "Comments":       "I was trying to create a Cartridge object to be passed to the CoffeeMaker Object. It has been partially successful. The bug I am having the most problem with is the CoffeeMaker detecting the Cartridge object - coffee type not found (ie name == 'NA') "

**Comment by drmikeh** [comment]
I like the splitting of Cartridge to a separate class. The water level should be a separate responsibility outside of the Cartridge class. The Cartridge class only deals with coffee flavors. The CoffeeMachine would manage the water level and delegate to the Cartridge class to handle coffee state and behavior.

**Comment by drmikeh** [comment]
The homework was to code the VendingMachine that serves up Hacker Cola.

**Comment by drmikeh** [comment]
Looks very good :+1:

**Pull request closed without merging**
